package report

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/ppiankov/ecrspectre/internal/policy"
	"github.com/ppiankov/ecrspectre/internal/registry"
	"github.com/ppiankov/ecrspectre/internal/retention"
)

// WO-14: defaultUntaggedDays is the untagged-image expiry used when unset.
const defaultUntaggedDays = 7

// WO-14: PolicyReporter emits a recommended ECR lifecycle policy + per-repo apply
// commands. Read-only — it only prints; never calls put-lifecycle-policy.
type PolicyReporter struct {
	Writer io.Writer
}

// WO-14: Generate writes the recommended lifecycle policy and apply commands.
func (r *PolicyReporter) Generate(data Data) error {
	cfg := policy.PolicyConfig{
		StaleDays:    data.Config.StaleDays,
		UntaggedDays: defaultUntaggedDays,
		KeepLatestN:  data.Config.Retention.KeepLatestN,
	}
	cfg.ProtectTags = data.Config.Retention.ProtectTags
	if len(cfg.ProtectTags) == 0 {
		cfg.ProtectTags = retention.DefaultProtectTags()
	}
	js, err := policy.GeneratePolicyJSON(cfg)
	if err != nil {
		return fmt.Errorf("generate lifecycle policy: %w", err)
	}

	w := &errWriter{w: r.Writer}
	w.println("# Recommended ECR lifecycle policy — review before applying.")
	w.println("# Generated by ecrspectre from the scan config. Save as ecrspectre-policy.json")
	w.println("# and apply per repository. Read-only: ecrspectre does NOT apply it for you.")
	w.println("")
	w.printf("%s\n", js)
	w.println("")

	repos := distinctRepos(data.Findings)
	if len(repos) == 0 {
		w.println("# (no image findings surfaced repositories in this scan;")
		w.println("#  apply the policy above to each ECR repository as appropriate.)")
	} else {
		w.println("# Apply to each scanned repository:")
		for _, repo := range repos {
			w.printf("#   aws ecr put-lifecycle-policy --repository %s --policy-text file://ecrspectre-policy.json\n", repo)
		}
	}
	writeWarnings(w, data.Errors)
	return w.err
}

// WO-14: writeWarnings appends a capped warnings section so a partial/throttled
// scan is visible — without it, an incomplete policy or delete-script looks complete.
func writeWarnings(w *errWriter, errors []string) {
	if len(errors) == 0 {
		return
	}
	w.println("")
	w.printf("# Warnings (%d): scan encountered errors — this output may be incomplete.\n", len(errors))
	const maxWarn = 20
	for i, e := range errors {
		if i >= maxWarn {
			w.printf("#   ... and %d more (re-run with --format text for the full list)\n", len(errors)-maxWarn)
			break
		}
		w.printf("#   - %s\n", e)
	}
}

// WO-14: distinctRepos returns sorted, de-duplicated repo names from image findings.
func distinctRepos(findings []registry.Finding) []string {
	seen := make(map[string]bool)
	var repos []string
	for _, f := range findings {
		if f.ResourceType != registry.ResourceImage {
			continue
		}
		repo := repoOf(f.ResourceID)
		if repo == "" || seen[repo] {
			continue
		}
		seen[repo] = true
		repos = append(repos, repo)
	}
	sort.Strings(repos)
	return repos
}

// WO-14: repoOf extracts the repo name from "repo@digest" or "repo:tag".
func repoOf(resourceID string) string {
	if i := strings.IndexByte(resourceID, '@'); i >= 0 {
		return resourceID[:i]
	}
	if i := strings.IndexByte(resourceID, ':'); i >= 0 {
		return resourceID[:i]
	}
	return resourceID
}
